### ISSUE TITLE
import neuralnet fails at basic level

### ISSUE THREAD

**Issue by jdgh000** [bips-hb/neuralnet#45]
I am not sure how you manage to break at such basic level: import, but does not work. 

python -c "import neuralnet"

[root@localhost ch11-nn-from-scratch]# pip3 list | grep neuralnet
neuralnet           0.2.0
[root@localhost ch11-nn-from-scratch]#

  self.ctor = getattr(np, o_type.dtype)
Traceback (most recent call last):
  File "/root/gg/git/codelab/gpu/ml/pytorch/pt/ml-with-pt-and-sk/ch11-nn-from-scratch/p352.py", line 1, in <module>
    from neuralnet import NeuralNetMLP
  File "/usr/local/lib/python3.9/site-packages/neuralnet/__init__.py", line 4, in <module>
    from .layers import *
  File "/usr/local/lib/python3.9/site-packages/neuralnet/layers.py", line 8, in <module>
    import theano
  File "/usr/local/lib/python3.9/site-packages/theano/__init__.py", line 124, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python3.9/site-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python3.9/site-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/usr/local/lib/python3.9/site-packages/theano/tensor/__init__.py", line 8, in <module>
    from theano.tensor.basic import *
  File "/usr/local/lib/python3.9/site-packages/theano/tensor/basic.py", line 20, in <module>
    from theano.scalar import int32 as int32_t
  File "/usr/local/lib/python3.9/site-packages/theano/scalar/__init__.py", line 3, in <module>
    from .basic import *
  File "/usr/local/lib/python3.9/site-packages/theano/scalar/basic.py", line 2370, in <module>
    convert_to_bool = Cast(bool, name='convert_to_bool')
  File "/usr/local/lib/python3.9/site-packages/theano/scalar/basic.py", line 2323, in __init__
    self.ctor = getattr(np, o_type.dtype)
  File "/usr/local/lib64/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'

**Comment by mnwright** [comment]
This is the repo of the **R** package neuralnet.
